server:
  port: 5003
spring:
  application:
    name: seata-busi
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.128:3307/enjoy2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
tx-seata:
  applicationId: enjoy-busi
  txServiceGroup: enjoy-tx-group
zookeeper:
  url: zookeeper://192.168.0.128:2181
dubbo:
  name: seata-busi
  port: 20881