server:
  port: 8090
spring:
  application:
    name: lcn-busi
  datasource:
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.128:3307/enjoy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
zookeeper:
  url: zookeeper://192.168.0.128:2181
dubbo:
  name: lcn-busi
  port: 20880

